# Generated by Django 3.2.13 on 2022-08-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0008_template'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailtransaksi',
            table='Produksi_Segmentasi',
        ),
    ]
