# Generated by Django 3.2.13 on 2022-08-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0009_alter_detailtransaksi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabang',
            table='Branch',
        ),
    ]
