# Generated by Django 3.2.13 on 2022-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0010_alter_cabang_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabang',
            table='cabang',
        ),
    ]
