# Generated by Django 3.2.13 on 2022-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0012_alter_cabang_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='captive_non_captive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(max_length=10)),
                ('captive_non_captive', models.CharField(max_length=10)),
                ('total', models.FloatField()),
            ],
        ),
    ]
