# Generated by Django 3.2.13 on 2022-08-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0013_captive_non_captive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captive_non_captive',
            options={'managed': False},
        ),
    ]
