# Generated by Django 3.2.13 on 2022-09-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0014_alter_captive_non_captive_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='captive_non_captive',
            table='captive_non_captive',
        ),
    ]
