# Generated by Django 3.2.13 on 2022-09-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0015_alter_captive_non_captive_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabang',
            table='cabang_2',
        ),
    ]
