# Generated by Django 3.2.13 on 2022-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0016_alter_cabang_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cabang',
            fields=[
                ('branch', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=255)),
                ('Jenis', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cabang_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_cabang_report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField(blank=True, null=True)),
                ('kode_cabang', models.CharField(max_length=10)),
                ('cabang_report', models.CharField(max_length=50)),
                ('premi', models.IntegerField()),
            ],
            options={
                'db_table': 'cabang_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_produksi_segmentasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('mo_care', models.CharField(max_length=50)),
                ('mo_care_name', models.CharField(max_length=50)),
                ('branchsupervisi', models.CharField(max_length=50)),
                ('branchsupervisi_name', models.CharField(max_length=50)),
                ('Branch_utama', models.CharField(max_length=50)),
                ('branchName_utama', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('branchName', models.CharField(max_length=50)),
                ('captive_non_captive', models.CharField(max_length=50)),
                ('Premi_WHOLESALE', models.FloatField()),
                ('premi_mikro', models.FloatField()),
                ('premi_ritel', models.FloatField()),
                ('Premi_RITEL_MIKRO', models.FloatField()),
                ('Premi_DIGITAL', models.FloatField()),
                ('Premi_SYARIAH', models.FloatField()),
                ('Premi_Total', models.FloatField()),
            ],
            options={
                'db_table': 'Produksi_Segmentasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_template',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('nama_template', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.IntegerField(blank=True, null=True)),
                ('periode', models.CharField(blank=True, max_length=255, null=True)),
                ('data_report', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cabang',
        ),
        migrations.DeleteModel(
            name='DetailTransaksi',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
