# Generated by Django 3.2.13 on 2022-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0017_auto_20220914_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_captive_non_captive_report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tanggal_produksi', models.DateField(blank=True, null=True)),
                ('kode_cabang', models.CharField(max_length=10)),
                ('cabang', models.CharField(max_length=50)),
                ('segmentasi_cnc', models.CharField(max_length=25)),
                ('premi', models.FloatField()),
            ],
            options={
                'db_table': 'captive_non_captive_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_marketing_officer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField(blank=True, null=True)),
                ('kode_cabang', models.CharField(max_length=10)),
                ('cabang', models.CharField(max_length=50)),
                ('nama_akun_mo', models.CharField(max_length=100)),
                ('nama_mo', models.CharField(max_length=150)),
                ('premi', models.FloatField()),
            ],
            options={
                'db_table': 'marketing_officer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_sourcename',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tgl_produksi', models.DateField(blank=True, null=True)),
                ('kode_cabang', models.CharField(max_length=10)),
                ('cabang', models.CharField(max_length=50)),
                ('kode_sumber', models.CharField(max_length=50)),
                ('sumber_bisnis', models.CharField(max_length=50)),
                ('premi', models.FloatField()),
            ],
            options={
                'db_table': 'sourcename',
                'managed': False,
            },
        ),
    ]
