# Generated by Django 4.1.7 on 2023-02-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0019_delete_kodeproduk_alter_captive_non_captive_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_brisurfnonbrisurf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('BRANCH', models.IntegerField()),
                ('branchName', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=11)),
                ('Premi', models.FloatField()),
            ],
            options={
                'db_table': 'premi_brisurfnonbrisurf',
                'managed': False,
            },
        ),
    ]
