# Generated by Django 3.2.13 on 2023-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0021_tbl_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_target_seg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BRANCH', models.CharField(max_length=255)),
                ('BRANCHNAME', models.CharField(max_length=255)),
                ('SEGMENT', models.CharField(max_length=255)),
                ('TARGET', models.FloatField()),
            ],
            options={
                'db_table': 'target_segmen',
                'managed': False,
            },
        ),
    ]
