# Generated by Django 3.2.13 on 2023-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0024_tbl_target_pusat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_persentase_pusat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=3)),
                ('branch_name', models.CharField(max_length=50)),
                ('persen_wholesale', models.FloatField()),
                ('persen_ritel', models.FloatField()),
                ('persen_mikro', models.FloatField()),
                ('persen_ritel_mikro', models.FloatField()),
                ('persen_syariah', models.FloatField()),
                ('persen_digital', models.FloatField()),
                ('persen_premi_total', models.FloatField()),
            ],
            options={
                'db_table': 'persentase_pusat',
                'managed': False,
            },
        ),
    ]
