# Generated by Django 3.2.13 on 2023-04-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0025_tbl_persentase_pusat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_persentase_target',
            table='persentase_segmentasi',
        ),
    ]
