# Generated by Django 3.2.13 on 2023-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0026_alter_tbl_persentase_target_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='persentase_mro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('premi_mikro_captive', models.FloatField()),
                ('premi_mikro_non_captive', models.FloatField()),
                ('premi_ritel_captive', models.FloatField()),
                ('premi_ritel_non_captive', models.FloatField()),
                ('premi_digital_captive', models.FloatField()),
                ('premi_digital_non_captive', models.FloatField()),
                ('premi_wholesale', models.FloatField()),
                ('premi_syariah', models.FloatField()),
            ],
            options={
                'db_table': 'persentase_mro',
                'managed': False,
            },
        ),
    ]
