# Generated by Django 3.2.13 on 2023-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0027_persentase_mro'),
    ]

    operations = [
        migrations.CreateModel(
            name='target_mro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Target_Wholesale', models.BigIntegerField()),
                ('Target_Syariah', models.BigIntegerField()),
                ('Target_retail_digital_captive', models.BigIntegerField()),
                ('Target_Mikro_Captive', models.BigIntegerField()),
                ('Target_Retail_Digital_Non_Captive', models.BigIntegerField()),
                ('Target_Mikro_Non_Captive', models.BigIntegerField()),
                ('branch', models.IntegerField()),
            ],
            options={
                'db_table': 'target_mro',
                'managed': False,
            },
        ),
    ]
