# Generated by Django 3.2.13 on 2023-06-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0028_target_mro'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_os',
            table='OS_Cabang_2',
        ),
    ]
