# Generated by Django 3.2.13 on 2023-06-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0029_alter_tbl_os_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_klaim_cabang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=3)),
                ('NamaBranch', models.CharField(max_length=50)),
                ('Nilai', models.FloatField()),
            ],
            options={
                'db_table': 'Klaim_per_cabang',
                'managed': False,
            },
        ),
    ]
