# Generated by Django 3.2.13 on 2023-06-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0030_tbl_klaim_cabang'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_target_seg',
            table='tbl_target_segmen_bulan_2023',
        ),
    ]
