# Generated by Django 3.2.13 on 2023-06-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0031_alter_tbl_target_seg_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='target_mro',
            table='target_mro_bulanan_2023',
        ),
    ]
