# Generated by Django 3.2.13 on 2023-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0032_alter_target_mro_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sum_segmentasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=5)),
                ('wholesale', models.FloatField()),
                ('syariah', models.FloatField()),
                ('digital', models.FloatField()),
                ('Retail_Pos_BRI', models.FloatField()),
                ('Retail_Pos_umum', models.FloatField()),
                ('Mikro_Pos_BRI', models.FloatField()),
                ('Mikro_Pos_umum', models.FloatField()),
            ],
            options={
                'db_table': 'sum_segmentasi',
                'managed': False,
            },
        ),
    ]
